# Generated by Django 5.0.9 on 2025-01-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='path',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
