name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: 📂 Sync files to o2switch
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.lami9315.odns.fr
        username: rams@rams.lami9315.odns.fr
        password: XdX5KtB5tVa@
